### ISSUE TITLE
Information Request

### ISSUE THREAD

**Issue by PalaNolho** [EmpireWorld/unity-dijkstras-pathfinding#2]
Hi,

I was looking at the Graph script and I was wondeing if you could explain these:
- How did you make that "Shot Shorter Path" button.
- How did you make the lines between the game objects when the "graph" game object is selected?

Many thanks in advance

**Comment by hasanbayatme** [comment]
Hey there!

The button and lines are made using a Custom Editor class named `GraphEditor`, checkout the source here: https://github.com/hasanbayatme/unity-dijkstras-pathfinding/blob/master/Assets/Scripts/Editor/GraphEditor.cs

It uses Unity's Handles class for drawing the lines in the Scene View.
